# Generated by Django 6.0.2 on 2026-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('game_state', models.CharField(choices=[('InProgress', 'InProgress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=10)),
                ('guessed_letters', models.JSONField(default=list)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
            ],
        ),
    ]
